name = "1.12.2"
author = "samueldelimpio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "429cc4f393bdd8b17289a0ef6d6179a7c15370dfa279067a39b80bfc93118be4"

[versions]
forge = "0.5.6-alpha"
minecraft = "1.12.2"
