name = "1.12.2"
author = "samueldelimpio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d0980325a3f9a26ae72c60c27f689cd809fa732c9115c7f553adca5ab514bc8"

[versions]
forge = "0.5.6-alpha"
minecraft = "1.12.2"
