name = "1.12.2"
author = "samueldelimpio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0971e567689bf4121c88c8d60a1c00d35c63724014572b2f541a950feec05467"

[versions]
forge = "0.5.4-alpha"
minecraft = "1.12.2"
